//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHitchhikingSpots.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyHitchhikingSpots.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY HITCHHIKING SPOTS.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gave up.
        /// </summary>
        public static string AttemptResultGaveUpOption {
            get {
                return ResourceManager.GetString("AttemptResultGaveUpOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got a ride.
        /// </summary>
        public static string AttemptResultGotARideOption {
            get {
                return ResourceManager.GetString("AttemptResultGotARideOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy url.
        /// </summary>
        public static string CopyMapRouteButtonText {
            get {
                return ResourceManager.GetString("CopyMapRouteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current location.
        /// </summary>
        public static string CurrentLocationMapBalloonTitle {
            get {
                return ResourceManager.GetString("CurrentLocationMapBalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this spot?.
        /// </summary>
        public static string DeleteSpotConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteSpotConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string DeleteSpotConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteSpotConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot successfully deleted..
        /// </summary>
        public static string DeleteSpotSucceededMessage {
            get {
                return ResourceManager.GetString("DeleteSpotSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export data.
        /// </summary>
        public static string ExportDataButtonText {
            get {
                return ResourceManager.GetString("ExportDataButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong..
        /// </summary>
        public static string GetSpotNameFaultedMessage {
            get {
                return ResourceManager.GetString("GetSpotNameFaultedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This location seems to be already reverse-geocoded, do you really want it to be done again? Push &quot;Ok&quot; to continue..
        /// </summary>
        public static string GetSpotNameRedoConfirmation {
            get {
                return ResourceManager.GetString("GetSpotNameRedoConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City: {0}
        ///Country: {1}.
        /// </summary>
        public static string GetSpotNameSucceededMessage {
            get {
                return ResourceManager.GetString("GetSpotNameSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to got a ride.
        /// </summary>
        public static string GotARideButtonText {
            get {
                return ResourceManager.GetString("GotARideButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string HitchabilityAverageOption {
            get {
                return ResourceManager.GetString("HitchabilityAverageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string HitchabilityBadOption {
            get {
                return ResourceManager.GetString("HitchabilityBadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string HitchabilityGoodOption {
            get {
                return ResourceManager.GetString("HitchabilityGoodOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string HitchabilityNoAnswerOption {
            get {
                return ResourceManager.GetString("HitchabilityNoAnswerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senseless.
        /// </summary>
        public static string HitchabilitySenselessOption {
            get {
                return ResourceManager.GetString("HitchabilitySenselessOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string HitchabilityVeryGoodOption {
            get {
                return ResourceManager.GetString("HitchabilityVeryGoodOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string ListTabTitle {
            get {
                return ResourceManager.GetString("ListTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map created successfuly!.
        /// </summary>
        public static string MapEditFormCreateSucceededMessage {
            get {
                return ResourceManager.GetString("MapEditFormCreateSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MapEditFormNameText {
            get {
                return ResourceManager.GetString("MapEditFormNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string MapEditFormSaveButtonText {
            get {
                return ResourceManager.GetString("MapEditFormSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong.
        ///Your map might not had been created/updated..
        /// </summary>
        public static string MapEditFormSaveFaultedMessage {
            get {
                return ResourceManager.GetString("MapEditFormSaveFaultedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map updated successfuly!.
        /// </summary>
        public static string MapEditFormUpdateSucceededMessage {
            get {
                return ResourceManager.GetString("MapEditFormUpdateSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an Attempt Result..
        /// </summary>
        public static string MapItemEditAttemptResultMandatoryText {
            get {
                return ResourceManager.GetString("MapItemEditAttemptResultMandatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new spot.
        /// </summary>
        public static string MapItemEditCreateViewTitle {
            get {
                return ResourceManager.GetString("MapItemEditCreateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation saved successfully!.
        /// </summary>
        public static string MapItemEditEvaluateSaveSucceededText {
            get {
                return ResourceManager.GetString("MapItemEditEvaluateSaveSucceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluate spot.
        /// </summary>
        public static string MapItemEditEvaluateViewTitle {
            get {
                return ResourceManager.GetString("MapItemEditEvaluateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt Result.
        /// </summary>
        public static string MapItemEditFormAttemptResultText {
            get {
                return ResourceManager.GetString("MapItemEditFormAttemptResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string MapItemEditFormDateText {
            get {
                return ResourceManager.GetString("MapItemEditFormDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string MapItemEditFormDeleteButtonText {
            get {
                return ResourceManager.GetString("MapItemEditFormDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get more info.
        /// </summary>
        public static string MapItemEditFormGetSpotNameButtonText {
            get {
                return ResourceManager.GetString("MapItemEditFormGetSpotNameButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitchability.
        /// </summary>
        public static string MapItemEditFormHitchabilityText {
            get {
                return ResourceManager.GetString("MapItemEditFormHitchabilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MapItemEditFormMapText {
            get {
                return ResourceManager.GetString("MapItemEditFormMapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string MapItemEditFormNoteText {
            get {
                return ResourceManager.GetString("MapItemEditFormNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string MapItemEditFormSaveButtonText {
            get {
                return ResourceManager.GetString("MapItemEditFormSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string MapItemEditFormTimeText {
            get {
                return ResourceManager.GetString("MapItemEditFormTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting time.
        /// </summary>
        public static string MapItemEditFormWaitingTimeText {
            get {
                return ResourceManager.GetString("MapItemEditFormWaitingTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in minutes.
        /// </summary>
        public static string MapItemEditFormWaitingTimeUnitText {
            get {
                return ResourceManager.GetString("MapItemEditFormWaitingTimeUnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select one of the options for Hitchability..
        /// </summary>
        public static string MapItemEditHitchabilityMandatoryText {
            get {
                return ResourceManager.GetString("MapItemEditHitchabilityMandatoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Time must be a number..
        /// </summary>
        public static string MapItemEditInvalidWaitingTimeText {
            get {
                return ResourceManager.GetString("MapItemEditInvalidWaitingTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update saved successfully!.
        /// </summary>
        public static string MapItemEditUpdateSucceededText {
            get {
                return ResourceManager.GetString("MapItemEditUpdateSucceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit spot.
        /// </summary>
        public static string MapItemEditUpdateViewTitle {
            get {
                return ResourceManager.GetString("MapItemEditUpdateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don\&apos;t have an internet connection right now or for some other reason your map may not load.
        ///Don\&apos;t worry! You can keep using the app normally because thanks to your GPS we still know exactly where you are and therefore you can normally save your current location as a spot and check it later! ;).
        /// </summary>
        public static string MapNotWorkingDialogMessage {
            get {
                return ResourceManager.GetString("MapNotWorkingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline mode.
        /// </summary>
        public static string MapNotWorkingDialogTitle {
            get {
                return ResourceManager.GetString("MapNotWorkingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new.
        /// </summary>
        public static string MapsViewCreateNewButtonText {
            get {
                return ResourceManager.GetString("MapsViewCreateNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maps.
        /// </summary>
        public static string MapsViewTitle {
            get {
                return ResourceManager.GetString("MapsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselect map.
        /// </summary>
        public static string MapsViewUnselectMapButtonText {
            get {
                return ResourceManager.GetString("MapsViewUnselectMapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string MapTabTitle {
            get {
                return ResourceManager.GetString("MapTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string MapViewTitle {
            get {
                return ResourceManager.GetString("MapViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.
        /// </summary>
        public static string RecordButtonText {
            get {
                return ResourceManager.GetString("RecordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url copied to clipboard..
        /// </summary>
        public static string RouteMapUrlCopiedMessage {
            get {
                return ResourceManager.GetString("RouteMapUrlCopiedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spots.
        /// </summary>
        public static string SpotsViewTitle {
            get {
                return ResourceManager.GetString("SpotsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show on map.
        /// </summary>
        public static string ViewOnMapButtonText {
            get {
                return ResourceManager.GetString("ViewOnMapButtonText", resourceCulture);
            }
        }
    }
}
