#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MyHitchhikingSpots.Resource", IsApplication=true)]

namespace MyHitchhikingSpots
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::MyHitchhikingSpots.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::MyHitchhikingSpots.Resource.String.Hello;
		}
		
		public partial class IdMainView_Action
		{
			
			// aapt resource value: 0x7f0d0002
			public const int LogOut = 2131558402;
			
			// aapt resource value: 0x7f0d0000
			public const int Sync = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int SyncLogs = 2131558401;
			
			static IdMainView_Action()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private IdMainView_Action()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010018
			public const int buyButtonAppearance = 2130771992;
			
			// aapt resource value: 0x7f010015
			public const int buyButtonHeight = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int buyButtonText = 2130771991;
			
			// aapt resource value: 0x7f010016
			public const int buyButtonWidth = 2130771990;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010012
			public const int environment = 2130771986;
			
			// aapt resource value: 0x7f010014
			public const int fragmentMode = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int fragmentStyle = 2130771987;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f01001b
			public const int maskedWalletDetailsBackground = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int maskedWalletDetailsButtonBackground = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int maskedWalletDetailsButtonTextAppearance = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public const int maskedWalletDetailsHeaderTextAppearance = 2130771994;
			
			// aapt resource value: 0x7f01001f
			public const int maskedWalletDetailsLogoImageType = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int maskedWalletDetailsLogoTextColor = 2130771998;
			
			// aapt resource value: 0x7f010019
			public const int maskedWalletDetailsTextAppearance = 2130771993;
			
			// aapt resource value: 0x7f010011
			public const int theme = 2130771985;
			
			// aapt resource value: 0x7f010009
			public const int uiCompass = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiRotateGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiScrollGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiTiltGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomControls = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int useViewLifecycle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int zOrderOnTop = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05001d
			public const int assignmentblue = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int assignmentgrey = 2131034142;
			
			// aapt resource value: 0x7f05001c
			public const int assignmentoffwhite = 2131034140;
			
			// aapt resource value: 0x7f050018
			public const int blueassignmentbutton = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int blueclick = 2131034135;
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f050026
			public const int common_signin_btn_text_dark = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int common_signin_btn_text_light = 2131034151;
			
			// aapt resource value: 0x7f050021
			public const int confirmationborder = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int greybutton = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int greyheadertext = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int greyspinnertext = 2131034138;
			
			// aapt resource value: 0x7f050023
			public const int historycolor = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int itemssearchcolor = 2131034144;
			
			// aapt resource value: 0x7f050024
			public const int light_grey = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int listviewdivider = 2131034146;
			
			// aapt resource value: 0x7f05001f
			public const int navigationitemselected = 2131034143;
			
			// aapt resource value: 0x7f050025
			public const int selectedItemBackGround = 2131034149;
			
			// aapt resource value: 0x7f05000f
			public const int wallet_bright_foreground_disabled_holo_light = 2131034127;
			
			// aapt resource value: 0x7f05000a
			public const int wallet_bright_foreground_holo_dark = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int wallet_bright_foreground_holo_light = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int wallet_dim_foreground_disabled_holo_dark = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int wallet_dim_foreground_holo_dark = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int wallet_dim_foreground_inverse_disabled_holo_dark = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int wallet_dim_foreground_inverse_holo_dark = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int wallet_highlighted_text_holo_dark = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int wallet_highlighted_text_holo_light = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int wallet_hint_foreground_holo_dark = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int wallet_hint_foreground_holo_light = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int wallet_holo_blue_light = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int wallet_link_text_light = 2131034134;
			
			// aapt resource value: 0x7f050028
			public const int wallet_primary_text_holo_light = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int wallet_secondary_text_holo_dark = 2131034153;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080004
			public const int jobImageContainer_height = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int jobImageContainer_width = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int list_padding = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int shadow_width = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int slidingmenu_offset = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgroundSuggestion1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int beaconbg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int businessman = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonBlack = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ButtonBlue = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ButtonGreen = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ButtonRed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ButtonYellow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int calendar_1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cancel = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int chart_gantt = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int check = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int checks = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int clock = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int collapsed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_disabled_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_disabled_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_disabled_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_focus_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_focus_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_normal_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_normal_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_pressed_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_icon_pressed_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_disabled_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_disabled_focus_dark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_disabled_focus_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_disabled_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_focus_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_focus_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_normal_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_normal_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_pressed_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_signin_btn_text_pressed_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ControlBackground = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ControlBackgroundWithHeader = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int get_directions_button = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Gradient_Background = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int house = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_action_camera = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_action_full_screen = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_action_new_picture = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_action_picture = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_action_refresh = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_launcher = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_plusone_medium_off_client = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_plusone_small_off_client = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_plusone_standard_off_client = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_plusone_tall_off_client = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Icon = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int information = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ItemPopupDivider = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int MapIcon = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int mapOverlay = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int MapOverlayDirections = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int MapOverlayDirectionsDown = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int MapOverlayDivider = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int MapOverlayIcon = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int MapOverlayIconDown = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int MiniviewBackground = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int myhitchhikingspots_icon = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int navigate_minus = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int navigate_plus = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int powered_by_google_dark = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int powered_by_google_light = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int shadow = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int SummaryRecord = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int TaskPaused = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int TaskRunning = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int telephone2 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int timer_selector = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int TimerPause = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int TimerRecord = 2130837581;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000e
			public const int book_now = 2131361806;
			
			// aapt resource value: 0x7f0a0026
			public const int boxBasicForm = 2131361830;
			
			// aapt resource value: 0x7f0a002c
			public const int boxEvaluationForm = 2131361836;
			
			// aapt resource value: 0x7f0a0031
			public const int boxOptions = 2131361841;
			
			// aapt resource value: 0x7f0a001e
			public const int btnCopyUrl = 2131361822;
			
			// aapt resource value: 0x7f0a0033
			public const int btnDelete = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int btnGetMoreInfo = 2131361844;
			
			// aapt resource value: 0x7f0a001b
			public const int btnGotARide = 2131361819;
			
			// aapt resource value: 0x7f0a001a
			public const int btnRecord = 2131361818;
			
			// aapt resource value: 0x7f0a0032
			public const int btnSave = 2131361842;
			
			// aapt resource value: 0x7f0a0023
			public const int button1 = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int button2 = 2131361828;
			
			// aapt resource value: 0x7f0a000a
			public const int buyButton = 2131361802;
			
			// aapt resource value: 0x7f0a000f
			public const int buy_now = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int buy_with_google = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int classic = 2131361809;
			
			// aapt resource value: 0x7f0a0029
			public const int dateDisplay = 2131361833;
			
			// aapt resource value: 0x7f0a0012
			public const int grayscale = 2131361810;
			
			// aapt resource value: 0x7f0a0005
			public const int holo_dark = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int holo_light = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0019
			public const int linearLayout1 = 2131361817;
			
			// aapt resource value: 0x7f0a0016
			public const int linearLayout2 = 2131361814;
			
			// aapt resource value: 0x7f0a001c
			public const int listTab = 2131361820;
			
			// aapt resource value: 0x7f0a002e
			public const int lstAttemptResult = 2131361838;
			
			// aapt resource value: 0x7f0a0028
			public const int lstHitchability = 2131361832;
			
			// aapt resource value: 0x7f0a0030
			public const int lstMap = 2131361840;
			
			// aapt resource value: 0x7f0a002f
			public const int lstMapTitle = 2131361839;
			
			// aapt resource value: 0x7f0a0014
			public const int map = 2131361812;
			
			// aapt resource value: 0x7f0a0022
			public const int mapOverlayAddress = 2131361826;
			
			// aapt resource value: 0x7f0a0021
			public const int mapOverlayDivider = 2131361825;
			
			// aapt resource value: 0x7f0a0020
			public const int mapOverlayGetDirections = 2131361824;
			
			// aapt resource value: 0x7f0a0017
			public const int mapTab = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int mapWithOverlay = 2131361816;
			
			// aapt resource value: 0x7f0a000c
			public const int match_parent = 2131361804;
			
			// aapt resource value: 0x7f0a0013
			public const int monochrome = 2131361811;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a001f
			public const int overlayDirectionsLayout = 2131361823;
			
			// aapt resource value: 0x7f0a002a
			public const int pickDate = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int pickTime = 2131361835;
			
			// aapt resource value: 0x7f0a0007
			public const int production = 2131361799;
			
			// aapt resource value: 0x7f0a0025
			public const int relativeLayout1 = 2131361829;
			
			// aapt resource value: 0x7f0a0008
			public const int sandbox = 2131361800;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a000b
			public const int selectionDetails = 2131361803;
			
			// aapt resource value: 0x7f0a001d
			public const int spotsList = 2131361821;
			
			// aapt resource value: 0x7f0a0009
			public const int strict_sandbox = 2131361801;
			
			// aapt resource value: 0x7f0a0015
			public const int tabHost1 = 2131361813;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0027
			public const int txtNote = 2131361831;
			
			// aapt resource value: 0x7f0a002d
			public const int txtWaitingTime = 2131361837;
			
			// aapt resource value: 0x7f0a000d
			public const int wrap_content = 2131361805;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int jobImage_height = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int jobImage_width = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int num_cols = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BasicDemo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MapInfoWindow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MapOverlayLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MapTab = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SpotEdit = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int spotsList_ListItem = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class MapInfoWindow
		{
			
			// aapt resource value: 0x7f0b0001
			public const int note = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int title = 2131427328;
			
			static MapInfoWindow()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private MapInfoWindow()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int MainView = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class SpotsList
		{
			
			// aapt resource value: 0x7f0c0003
			public const int btnEdit = 2131492867;
			
			// aapt resource value: 0x7f0c0002
			public const int btnZoomIn = 2131492866;
			
			// aapt resource value: 0x7f0c0001
			public const int txtNote = 2131492865;
			
			// aapt resource value: 0x7f0c0000
			public const int txtTitle = 2131492864;
			
			static SpotsList()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private SpotsList()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001f
			public const int AppBarButtonText = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int ApplicationName = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int ApplicationTitle = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int AttemptResultGaveUpOption = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int AttemptResultGotARideOption = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int CopyMapRouteButtonText = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int CurrentLocationMapBalloonTitle = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int DeleteSpotConfirmationMessage = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int DeleteSpotConfirmationTitle = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int DeleteSpotSucceededMessage = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int GetSpotNameFaultedMessage = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int GetSpotNameRedoConfirmation = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int GetSpotNameSucceededMessage = 2131099689;
			
			// aapt resource value: 0x7f060056
			public const int GoogleMapsAPIKey = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int GoogleMapsKeyIssue = 2131099735;
			
			// aapt resource value: 0x7f06002a
			public const int GotARideButtonText = 2131099690;
			
			// aapt resource value: 0x7f06001a
			public const int Hello = 2131099674;
			
			// aapt resource value: 0x7f06002b
			public const int HitchabilityAverageOption = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int HitchabilityBadOption = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int HitchabilityGoodOption = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int HitchabilityNoAnswerOption = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int HitchabilitySenselessOption = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int HitchabilityVeryGoodOption = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int ListTabTitle = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int MapEditFormCreateSucceededMessage = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int MapEditFormNameText = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int MapEditFormSaveButtonText = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int MapEditFormSaveFaultedMessage = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int MapEditFormUpdateSucceededMessage = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int MapItemEditAttemptResultMandatoryText = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int MapItemEditCreateViewTitle = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int MapItemEditEvaluateSaveSucceededText = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int MapItemEditEvaluateViewTitle = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int MapItemEditFormAttemptResultText = 2131099707;
			
			// aapt resource value: 0x7f060052
			public const int MapItemEditFormChangeDateButtonText = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int MapItemEditFormChangeTimeButtonText = 2131099731;
			
			// aapt resource value: 0x7f06003c
			public const int MapItemEditFormDateText = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int MapItemEditFormDeleteButtonText = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int MapItemEditFormGetSpotNameButtonText = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int MapItemEditFormHitchabilityText = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int MapItemEditFormMapText = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int MapItemEditFormNoteText = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int MapItemEditFormSaveButtonText = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int MapItemEditFormTimeText = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int MapItemEditFormWaitingTimeText = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int MapItemEditFormWaitingTimeUnitText = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int MapItemEditHitchabilityMandatoryText = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int MapItemEditInvalidWaitingTimeText = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int MapItemEditUpdateSucceededText = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int MapItemEditUpdateViewTitle = 2131099721;
			
			// aapt resource value: 0x7f060055
			public const int MapNotWorkingDialogMessage = 2131099733;
			
			// aapt resource value: 0x7f060054
			public const int MapNotWorkingDialogTitle = 2131099732;
			
			// aapt resource value: 0x7f06004d
			public const int MapTabTitle = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int MapViewTitle = 2131099726;
			
			// aapt resource value: 0x7f06004a
			public const int MapsViewCreateNewButtonText = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int MapsViewTitle = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int MapsViewUnselectMapButtonText = 2131099724;
			
			// aapt resource value: 0x7f06004f
			public const int RecordButtonText = 2131099727;
			
			// aapt resource value: 0x7f06001c
			public const int ResourceFlowDirection = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int ResourceLanguage = 2131099677;
			
			// aapt resource value: 0x7f060050
			public const int RouteMapUrlCopiedMessage = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int SpotsViewTitle = 2131099729;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_enable_button = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_enable_text = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_enable_title = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_error_notification_requested_by_msg = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_install_button = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_text_phone = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_text_tablet = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_title = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_invalid_account_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_invalid_account_title = 2131099664;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_needs_enabling_title = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_network_error_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_network_error_title = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_notification_needs_installation_title = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_notification_needs_update_title = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_notification_ticker = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_unknown_issue = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_unsupported_date_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_unsupported_text = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_unsupported_title = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_update_button = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_update_text = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_update_title = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int common_signin_button_text = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int common_signin_button_text_long = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int wallet_buy_button_place_holder = 2131099673;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040005
			public const int ButtonText = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int CustomDialogTheme = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int CustomHoloTheme = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int FildDescription = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int HeaderText = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int ListView = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int Theme_IAPTheme = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int WalletFragmentDefaultButtonTextAppearance = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int WalletFragmentDefaultDetailsHeaderTextAppearance = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int WalletFragmentDefaultDetailsTextAppearance = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int WalletFragmentDefaultStyle = 2130968580;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] MapAttrs = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] WalletFragmentOptions = new int[]
			{
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 1
			public const int WalletFragmentOptions_environment = 1;
			
			// aapt resource value: 3
			public const int WalletFragmentOptions_fragmentMode = 3;
			
			// aapt resource value: 2
			public const int WalletFragmentOptions_fragmentStyle = 2;
			
			// aapt resource value: 0
			public const int WalletFragmentOptions_theme = 0;
			
			public static int[] WalletFragmentStyle = new int[]
			{
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999};
			
			// aapt resource value: 3
			public const int WalletFragmentStyle_buyButtonAppearance = 3;
			
			// aapt resource value: 0
			public const int WalletFragmentStyle_buyButtonHeight = 0;
			
			// aapt resource value: 2
			public const int WalletFragmentStyle_buyButtonText = 2;
			
			// aapt resource value: 1
			public const int WalletFragmentStyle_buyButtonWidth = 1;
			
			// aapt resource value: 6
			public const int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
			
			// aapt resource value: 8
			public const int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
			
			// aapt resource value: 7
			public const int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
			
			// aapt resource value: 5
			public const int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
			
			// aapt resource value: 10
			public const int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
			
			// aapt resource value: 9
			public const int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
			
			// aapt resource value: 4
			public const int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
